/*
───────────────────────────────────────────────────────────────
🧳 UVa 10460 Find the Permuted String, https://onlinejudge.org/external/104/10460.pdf, rt: s
───────────────────────────────────────────────────────────────
 * ============================================================================
 * ALGORITHM: THE GUIDED BACKTRACKING PATTERN (Direct Permutation Path)
 * ============================================================================
 * THE CORE PROBLEM:
 * We need to generate the exact K-th lexicographical permutation of a string 
 * of length N. A standard backtracking search takes O(N!) time, which is 
 * completely impossible for N >= 10.
 * 
 * THE ARCHITECTURAL WIN (The "Guided" Backtracking):
 * Instead of searching, we precalculate the "Block Indices" of our target path 
 * (the 'breadcrumbs' through the permutation tree) and store them in `path`.
 * 
 * 1. THE PERMUTATION-TO-BLOCK FORMULA:
 *    At any level S (the current size of our permutation), each parent block 
 *    of index `block` splits into exactly `S + 1` children. 
 *    The mathematical index of the child block generated by inserting at 
 *    position 'i' is:
 *         next_block_idx = (block * (S + 1)) + i
 * 
 * 2. THE "LOCK AND KEY" GUARD:
 *    Inside our loop, we evaluate this index:
 *         if (next_block_idx == path[path_idx])
 * 
 *    This guard acts as an absolute filter. Even though the `for` loop has 
 *    S + 1 options, the guard only unlocks for the EXACT insertion index 
 *    that lies on the winning path.
 * 
 * 3. THE "BACKTRACKING" ELEGANCE:
 *    Unlike a pure mathematical list-unrolling, keeping the `insert`/`erase` 
 *    backtracking structure is highly beneficial. It keeps the code extremely 
 *    flexible. If the problem ever added a secondary constraint (e.g. "no two 
 *    vowels adjacent"), you could easily add it to this loop!
 * 
 * COMPLEXITY:
 * - Time:  O(N^2) — The recursion depth is N, and at each level, the loop 
 *          only enters the valid branch once. Total operations ≈ 400 (for N=20).
 * - Space: O(N) — Sized strictly to the recursion stack.
 * ============================================================================
*/

#include "../debug.h"
#include "../../aux.h"
#include <bits/stdc++.h>



std::string permutation;


// Converts the target permutation rank into the exact sequence of insertion indices
std::vector<int> get_insertion_path(int target, int N) {
    std::vector<int> path(N);
    int curr = target;

    // Unroll from the final level N down to 1
    for (int S = N; S >= 1; --S) {
        path[S - 1] = curr / S; // The remainder is the exact insertion index 'i'!
        curr /= S;             // Move up to the parent block index
    }
    path.push_back(target);
    return path;
}


void backtrack(const std::string& str, int pos, std::string& curr_permutation, int block, const std::vector<int>& path, int path_idx) {

    if(pos == (int)str.size()) {
      permutation = curr_permutation;
      return;
    }
    
  
    int S = (int)curr_permutation.size();
    for(int i = 0; i <= S; ++i) {
      // THE FORMULA: 
      // parent_block_index * (number of children at this level) + insertion_index
      int next_block_idx = (block * (S + 1)) + i;
      if(next_block_idx == path[path_idx]) {
        curr_permutation.insert(i, 1, str[pos]);
        backtrack(str, pos + 1, curr_permutation, next_block_idx, path, path_idx + 1);
        curr_permutation.erase(i, 1);
      }
    }

}


namespace algorithms::onlinejudge::complete_search::permuted_string
{

    void submit(std::optional<char*> file, bool debug_mode)
    {
        if (file.has_value()) {
          // Attempt to reopen stdin with the provided file
          if (std::freopen(file.value(), "r", stdin) == nullptr) {
            // If freopen fails, throw an exception with a more detailed error message
            std::string name = file.value();
            std::string errorMessage = 
              "Failed to open file: " + name +
              " with error: " + std::strerror(errno);
            throw std::ios_base::failure(errorMessage);
          }
        }

        int t_cases;
        std::cin >> t_cases;
        while(t_cases--) {
          std::string curr_permutation;
          std::string str;
          int target_index;
          std::cin >> str >> target_index;
          --target_index;
          auto path = get_insertion_path(target_index, (int)str.size());
          backtrack(str, 0, curr_permutation, 0, path, 1);
          std::cout << permutation << std::endl;
        }
    }
}